project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from .views import *

urlpatterns = [
    
    path('', project_page),
    path('create/', project_create),
    path('<str:project_name>/', project_detail),
    path('<str:project_name>/update/', project_update),
    path('<str:project_name>/delete/', project_delete),
    #path('media/', media_upload),

    ]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

session/urls.py
from django.urls import path
from .views import (
	news_list_view,
	news_create_view,
	news_detail_view,
	news_update_view,
	news_delete_view,
	activity_list_view,
	activity_create_view,
	activity_detail_view,
	activity_update_view,
	activity_delete_view
)
from uximhome.views import(
	session_page
)



urlpatterns = [
	path('',session_page),
	
	path('news/create/',news_create_view),
	path('news/<str:slug>/edit/',news_update_view),
	path('news/<str:slug>/delete/',news_delete_view),
	path('news/<str:slug>/',news_detail_view),
	path('news/',news_list_view),

	path('activity/create/',activity_create_view),
	path('activity/<str:slug>/edit/',activity_update_view),
	path('activity/<str:slug>/delete/',activity_delete_view),
	path('activity/<str:slug>/',activity_detail_view),
	path('activity/',activity_list_view),
	]

uximhome/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from users import views as user_views

from .views import *

from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_page),

    path('session/',include('session.urls')),
    path('project/',project_page),
    path('contact/',contact_page),
    path('about/',about_page),
    path('register/', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('accounts/', include('django.contrib.auth.urls')),
    #path('about/', include('about.urls')),
    #path('contact/', include('contact.urls')),
    path('project/', include('project.urls')),
    #path('session/', include('session.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

session/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
# Create your models here.

User = settings.AUTH_USER_MODEL #the only way

class ActivityPost(models.Model):
	#활동사진(사진, 날짜)
	slug = models.SlugField(unique=True, blank=True, null=False)
	user = models.ForeignKey(User, default=1, null=True, on_delete=models.SET_NULL) #bind a model(user) to another(newpost)
	image = models.ImageField(blank=True,upload_to="session/activity")

	publish_date = models.DateTimeField(auto_now_add=True, null=True) #when added to DB
	updated = models.DateTimeField(auto_now=True) #when click save

		#order of qs
	class Meta:
		ordering = ['-publish_date', '-updated']

	def get_absolute_url(self):
		return f"{self.slug}"



class NewsPost(models.Model):
	#유심뉴스(제목, 날짜, 작성자, 사진, 글 내용)
	slug = models.SlugField(unique=True, blank=True, null=False)
	user = models.ForeignKey(User, default=1, null=True, on_delete=models.SET_NULL) #bind a model(user) to another(newpost)
	title = models.CharField(max_length=120)
	content = models.TextField(null=True, blank=True)
	image = models.ImageField(blank=True, upload_to="session/news")

	publish_date = models.DateTimeField(auto_now_add=True, null=True) #when added to DB
	updated = models.DateTimeField(auto_now=True) #when click save

	#order of qs
	class Meta:
		ordering = ['-publish_date', '-updated']

	def get_absolute_url(self):
		return f"{self.slug}"

session/forms.py
from django import forms
from .models import ActivityPost,NewsPost

class NewsModelForm(forms.ModelForm):
	class Meta:
		model = NewsPost
		fields = ['title', 'content','image','slug']
		#fields to be used (django brings from model)

class ActivityModelForm(forms.ModelForm):
	class Meta:
		model = ActivityPost
		fields = ['image','slug']
		#fields to be used (django brings from model)

session/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required

from django.shortcuts import render, get_object_or_404, redirect

from .forms import NewsModelForm, ActivityModelForm
from .models import ActivityPost,NewsPost
#GET -> RETRIEVE / LIST
#POST -> CREATE / UPDATE / DELETE

def news_list_view(request):
	qs = NewsPost.objects.all() #objects -> django manager
	context={'object_list' : qs}
	return render(request, 'news/list.html', context)

def news_detail_view(request, slug):
	obj = get_object_or_404(NewsPost, slug=slug) #handles 404exceptions in 1 line
	context={"object": obj}
	return render(request, 'news/detail.html', context)

@staff_member_required
@login_required
def news_create_view(request):
	form = NewsModelForm(request.POST or None, request.FILES)
	if form.is_valid():
		obj = form.save(commit=False)
		obj.user = request.user #set current user
		obj.save()
		form = NewsModelForm() #reinitialize
	context={
		'form' : form
	}
	return render(request, 'news/create.html', context)

@staff_member_required
@login_required
def news_update_view(request,slug):
	obj = get_object_or_404(NewsPost, slug=slug) #lookup the object
	form = NewsModelForm(request.POST or None, instance=obj)
	if form.is_valid():
	 	form.save() #update current data
	context={'form': form,"title": f"Update {obj.title}"}
	return render(request, 'news/create.html', context)


@staff_member_required
@login_required
def news_delete_view(request,slug):
	obj = get_object_or_404(NewsPost, slug=slug) #lookup the object
	if request.method == "POST":
		obj.delete()
		return redirect('../../') #redirect
	context={"object": obj}
	return render(request, 'news/delete.html', context)



######################################################UXIMACTIVITY



def activity_list_view(request):
	qs = ActivityPost.objects.all() #objects -> django manager
	context={'object_list' : qs}
	return render(request, 'activity/list.html', context)

def activity_detail_view(request, slug):
	obj = get_object_or_404(ActivityPost, slug=slug) #handles 404exceptions in 1 line
	context={"object": obj}
	return render(request, 'activity/detail.html', context)

@staff_member_required
@login_required
def activity_create_view(request):
	form = ActivityModelForm(request.POST or None, request.FILES or None)
	if form.is_valid():
		obj = form.save(commit=False)
		obj.user = request.user #set current user
		obj.save()
		form = ActivityModelForm() #reinitialize
	context={
		'form' : form
	}
	return render(request, 'activity/create.html', context)

@staff_member_required
@login_required
def activity_update_view(request,slug):
	obj = get_object_or_404(NewsPost, slug=slug) #lookup the object
	form = ActivityModelForm(request.POST or None, instance=obj)
	if form.is_valid():
	 	form.save() #update current data
	context={'form': form,"title": f"Update {obj.title}"}
	return render(request, 'activity/create.html', context)


@staff_member_required
@login_required
def activity_delete_view(request,slug):
	obj = get_object_or_404(ActivityPost, slug=slug) #lookup the object
	if request.method == "POST":
		obj.delete()
		return redirect('../../') #redirect
	context={"object": obj}
	return render(request, 'activity/delete.html', context)

session/templates/news/create.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Contact V5</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->
	<link rel="icon" type="image/png" href="{%static 'images/icons/favicon.ico'%}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{%static 'vendor/bootstrap/css/bootstrap.min.css'%}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{%static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css'%}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{%static 'fonts/iconic/css/material-design-iconic-font.min.css'%}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{%static 'vendor/animate/animate.css'%}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{%static 'vendor/css-hamburgers/hamburgers.min.css'%}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{%static 'vendor/animsition/css/animsition.min.css'%}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{%static 'vendor/select2/select2.min.css'%}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{%static 'vendor/daterangepicker/daterangepicker.css'%}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{%static 'vendor/noui/nouislider.min.css'%}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{%static 'css/util.css'%}">
	<link rel="stylesheet" type="text/css" href="{%static 'css/main.css'%}">
<!--===============================================================================================-->
</head>
<body>

<form method='POST'enctype="multipart/form-data"> {% csrf_token %}

	<div class="container-contact100">
		<div class="wrap-contact100">
			<form class="contact100-form validate-form">
				<span class="contact100-form-title">
					UXIM NEWS
				</span>

				<div class="wrap-input100 validate-input bg1" data-validate="제목은 필수사항입니다">
					<span class="label-input100">TITLE</span>
					<input class="input100" type="text" name="name" placeholder="제목을 입력하세요">
				</div>

				<div class="wrap-input100 validate-input bg1">
					<input for="{{form.message.id_for_label}}">TITLE</input>
					{{form.title}}
					<style>
					input#id_title {
					    width: 50%;
					}
					</style>
				</div>

				<div class="wrap-input100 validate-input bg1 rs1-wrap-input100" data-validate = "Enter Your Email (e@a.x)">
					<span class="label-input100">DATE</span>
				</div>

				<div class="wrap-input100 bg1 rs1-wrap-input100">
					<span class="label-input100">EDITOR</span>
				</div>

				<div class="wrap-input100 validate-input bg0 rs1-alert-validate" data-validate = "Please Type Your Message">
					<span class="label-input100">CONTENTS</span>
					<textarea class="input100" name="message" placeholder="내용을 입력하세요"></textarea>
				</div>

				<div class="wrap-input100 validate-input bg0 rs1-alert-validate" data-validate = "Please Type Your Message">
					<span class="label-input100">IMAGES</span>
					<input type="file" class="input100" name="image" ></input>
				</div>

				<div class="container-contact100-form-btn">
					<button type="submit" class="contact100-form-btn">
						<span>
							UPLOAD
							<i class="fa fa-long-arrow-right m-l-7" aria-hidden="true"></i>
						</span>
					</button>
				</div>
			</form>
		</div>
	</div>


<!--===============================================================================================-->
	<script src="{%static 'vendor/jquery/jquery-3.2.1.min.js'%}"></script>
<!--===============================================================================================-->
	<script src="{%static 'vendor/animsition/js/animsition.min.js'%}"></script>
<!--===============================================================================================-->
	<script src="{%static 'vendor/bootstrap/js/popper.js'%}"></script>
	<script src="{%static 'vendor/bootstrap/js/bootstrap.min.js'%}"></script>
<!--===============================================================================================-->
	<script src="{%static 'vendor/select2/select2.min.js'%}"></script>
	<script>
		$(".js-select2").each(function(){
			$(this).select2({
				minimumResultsForSearch: 20,
				dropdownParent: $(this).next('.dropDownSelect2')
			});


			$(".js-select2").each(function(){
				$(this).on('select2:close', function (e){
					if($(this).val() == "Please chooses") {
						$('.js-show-service').slideUp();
					}
					else {
						$('.js-show-service').slideUp();
						$('.js-show-service').slideDown();
					}
				});
			});
		})
	</script>
<!--===============================================================================================-->
	<script src="{%static 'vendor/daterangepicker/moment.min.js'%}"></script>
	<script src="{%static 'vendor/daterangepicker/daterangepicker.js'%}"></script>
<!--===============================================================================================-->
	<script src="{%static 'vendor/countdowntime/countdowntime.js'%}"></script>
<!--===============================================================================================-->
	<script src="{%static 'vendor/noui/nouislider.min.js'%}"></script>
	<script>
	    var filterBar = document.getElementById('filter-bar');

	    noUiSlider.create(filterBar, {
	        start: [ 1500, 3900 ],
	        connect: true,
	        range: {
	            'min': 1500,
	            'max': 7500
	        }
	    });

	    var skipValues = [
	    document.getElementById('value-lower'),
	    document.getElementById('value-upper')
	    ];

	    filterBar.noUiSlider.on('update', function( values, handle ) {
	        skipValues[handle].innerHTML = Math.round(values[handle]);
	        $('.contact100-form-range-value input[name="from-value"]').val($('#value-lower').html());
	        $('.contact100-form-range-value input[name="to-value"]').val($('#value-upper').html());
	    });
	</script>
<!--===============================================================================================-->
	<script src="{%static 'js/main1.js'%}"></script>

<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-23581568-13');
</script>
</form>
</body>
</html>

session/templates/news/delete.html
{% extends "base.html" %}

{% block content %}

<form action='.' method='POST'> {% csrf_token %}
	<h1>Do you want to delete the product "{{object.title}}"?</h1>
	<h2>press yes to delete</h2>
	<p><input type='submit' value='Yes' /> <a href='../'>Cancel</a></p>
</form>

{% endblock %}

session/templates/news/detail.html
{% extends "base.html" %}

{% block content %}

<h1>{{object.title}}</h1>
<p>{{object.content|linebreaks}}{{object.publish_date|linebreaks}}{{object.updated}}</p>

{% if request.user.is_authenticated %}
	{% if request.user.is_staff %}
		<a href = './edit'>Edit</a>
		<a href = './delete'>Delete</a>
	{% endif %}
{% endif %}

{% endblock %}

session/templates/news/list.html
{% block content %}

	{% for object in object_list %}
		<li><a href='{{ object.get_absolute_url }}'>{{object.title}}{{object.image|linebreaks}}</a></li>
	{% endfor %}

{% endblock %}